# Generated by Django 4.1.3 on 2022-11-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0004_alter_imagehidden_image_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehidden',
            name='image_hidden',
            field=models.FilePathField(),
        ),
    ]
