# Generated by Django 4.1.3 on 2022-11-17 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0002_image_uploaded_by_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp'])]),
        ),
        migrations.AlterField(
            model_name='imagehidden',
            name='image_hidden',
            field=models.ImageField(upload_to='media/images-hidden/'),
        ),
    ]
